export type LocalTtsVoice = {
  id: string;
  modelId: string;
  name: string;
  desc: string;
  icon: string;
  theme: "primary" | "secondary" | "tertiary" | "neutral" | "error";
  speaker: number;
  available: boolean;
  rate: number;
  pitch: number;
  volume: number;
};

export const LOCAL_TTS_RUNTIME_CONFIG = {
  warmupText: "你好，欢迎体验语音合成。",
  engineModuleUrl: "/models/tts/piper-tts-web/piper-tts-web.js",
  onnxBasePath: "/models/tts/onnx/",
  piperBasePath: "/models/tts/piper/",
  voiceBaseUrl: "/models/tts/piper-voices/",
};

export const LOCAL_TTS_VOICES: LocalTtsVoice[] = [
  {
    id: "warm-female",
    modelId: "zh_CN-huayan-x_low",
    name: "温暖女声",
    desc: "温柔",
    icon: "☻",
    theme: "primary",
    speaker: 0,
    available: true,
    rate: 0.95,
    pitch: 1,
    volume: 85,
  },
  {
    id: "solemn-male",
    modelId: "zh_CN-chaowen-medium",
    name: "庄重男声",
    desc: "稳重",
    icon: "▣",
    theme: "secondary",
    speaker: 0,
    available: true,
    rate: 0.85,
    pitch: -4,
    volume: 85,
  },
  {
    id: "lively-child",
    modelId: "zh_CN-xiao_ya-medium",
    name: "活泼童声",
    desc: "可爱",
    icon: "☻",
    theme: "tertiary",
    speaker: 0,
    available: true,
    rate: 1.18,
    pitch: 5,
    volume: 88,
  },
  {
    id: "professional-broadcast",
    modelId: "zh_CN-chaowen-medium",
    name: "专业播音",
    desc: "大气",
    icon: "♩",
    theme: "neutral",
    speaker: 0,
    available: true,
    rate: 0.92,
    pitch: -1,
    volume: 90,
  },
  {
    id: "soft-narration",
    modelId: "zh_CN-xiao_ya-medium",
    name: "柔和解说",
    desc: "亲和",
    icon: "♟",
    theme: "secondary",
    speaker: 0,
    available: true,
    rate: 0.88,
    pitch: 2,
    volume: 82,
  },
  {
    id: "magnetic-male",
    modelId: "zh_CN-chaowen-medium",
    name: "磁性男声",
    desc: "深沉",
    icon: "♟",
    theme: "neutral",
    speaker: 0,
    available: true,
    rate: 0.82,
    pitch: -6,
    volume: 86,
  },
  {
    id: "sweet-female",
    modelId: "zh_CN-xiao_ya-medium",
    name: "甜美女声",
    desc: "元气",
    icon: "✾",
    theme: "error",
    speaker: 0,
    available: true,
    rate: 1.08,
    pitch: 4,
    volume: 86,
  },
  {
    id: "news-broadcast",
    modelId: "zh_CN-huayan-x_low",
    name: "新闻播报",
    desc: "标准",
    icon: "☚",
    theme: "tertiary",
    speaker: 0,
    available: true,
    rate: 1,
    pitch: 0,
    volume: 88,
  },
  {
    id: "audiobook",
    modelId: "zh_CN-huayan-x_low",
    name: "有声书",
    desc: "叙述",
    icon: "◧",
    theme: "secondary",
    speaker: 0,
    available: true,
    rate: 0.9,
    pitch: -2,
    volume: 84,
  },
  {
    id: "knowledge-explain",
    modelId: "zh_CN-huayan-x_low",
    name: "知识讲解",
    desc: "清晰",
    icon: "✉",
    theme: "primary",
    speaker: 0,
    available: true,
    rate: 0.98,
    pitch: 1,
    volume: 88,
  },
];
