// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/8 18:36:06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/11045/Desktop/mata-edu-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/11045/Desktop/mata-edu-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/11045/Desktop/mata-edu-web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/11045/Desktop/mata-edu-web/app/plugins/**/*.{js,ts,mjs}","C:/Users/11045/Desktop/mata-edu-web/app/composables/**/*.{js,ts,mjs}","C:/Users/11045/Desktop/mata-edu-web/app/utils/**/*.{js,ts,mjs}","C:/Users/11045/Desktop/mata-edu-web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/11045/Desktop/mata-edu-web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/11045/Desktop/mata-edu-web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/11045/Desktop/mata-edu-web/app/app.config.{js,ts,mjs}","C:/Users/11045/Desktop/mata-edu-web/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;